"""initial

Revision ID: 9f336b4c00bb
Revises: 
Create Date: 2026-03-17 11:49:19.603581

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from src.infrastructure.persistence.sqlalchemy.types import (  # noqa: F401
    UserEmailType,
    UserIdType,
    UserNameType,
)

# revision identifiers, used by Alembic.
revision: str = '9f336b4c00bb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', UserIdType(length=36), nullable=False),
    sa.Column('email', UserEmailType(length=255), nullable=False),
    sa.Column('name', UserNameType(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
